version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mariaines-test-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1akqsmxlhmhg2"
s3_prefix = "mariaines-test-sam"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Revision=\"1\""
